document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/cute-graphics.css">');
function goalNav(){return `<aside class="sidebar"><div class="brand">Ledger <span>V2</span></div><nav class="nav"><a href="index.html">Overview</a><a href="transactions.html">Transactions</a><a href="budgets.html">Budgets</a><a href="goals.html" class="active">Goals</a><a href="wishlist.html">Wishlist</a><a href="bills.html">Bills</a><a href="analytics.html">Analytics</a><a href="afford.html">Affordability</a><a href="accounts.html">Accounts</a><a href="settings.html">Settings</a></nav></aside>`}
window.render=()=>{
  document.body.innerHTML=`<div class="app">${goalNav()}<main><header class="topbar cute-hero"><div><h1>Savings goals</h1><p class="muted">Small deposits create meaningful progress.</p></div><button id="addGoal">Add goal</button></header><section id="goalGrid" class="goal-grid"></section></main></div><div class="modal" id="goalModal"><div class="dialog"><h2>New savings goal</h2><form id="goalForm"><label>Goal name<input required name="name" placeholder="Japan trip"></label><div class="form-grid"><label>Target amount<input required name="target" type="number" min="1" step=".01"></label><label>Target date<input name="deadline" type="date"></label></div><div class="dialog-foot"><button type="button" class="secondary" id="closeGoal">Cancel</button><button>Create goal</button></div></form></div></div><div class="modal" id="depositModal"><div class="dialog"><h2>Add money to goal</h2><p class="muted" id="depositGoalName" style="margin-bottom:13px"></p><form id="depositForm"><label>Amount<input required name="amount" type="number" min=".01" step=".01" placeholder="0.00"></label><label>Move money from<select required name="accountId" id="depositAccount"></select></label><div class="dialog-foot"><button type="button" class="secondary" id="closeDeposit">Cancel</button><button>Add money</button></div></form></div></div><div class="notice"></div>`;
  let activeGoalId=null;
  function paint(){let d=Storage.load();goalGrid.innerHTML=d.goals.map((g,i)=>{let pct=Math.min(100,Math.round((+g.saved||0)/(+g.target||1)*100)),left=Math.max(0,(+g.target||0)-(+g.saved||0));return `<article class="goal-premium ${pct===100?'goal-complete':''}" style="animation-delay:${i*.07}s"><div class="goal-icon">${pct===100?'★':'◌'}</div><p class="stat-label">SAVINGS GOAL</p><h2>${g.name}</h2><p class="goal-percent">${pct}%</p><div class="progress"><b style="width:${pct}%"></b></div><p class="muted">${Utils.money(g.saved)} of ${Utils.money(g.target)} · ${pct===100?'Complete':' '+Utils.money(left)+' left'}</p><div class="goal-actions"><button class="secondary" data-add="${g.id}">Add money</button><button class="secondary" data-delete="${g.id}">Delete</button></div></article>`}).join('')||'<div class="card empty cute-empty"><span class="cute-spark"></span><span><b>Start a goal.</b><br>Set aside even a small amount and watch it grow.</span></div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openDeposit(b.dataset.add));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{Storage.remove('goals',b.dataset.delete);paint();Utils.toast('Goal removed.')})}
  function openDeposit(id){let d=Storage.load(),g=d.goals.find(x=>x.id===id);activeGoalId=id;depositGoalName.textContent=g.name+' · '+Utils.money(g.saved)+' saved';depositAccount.innerHTML=d.accounts.map(a=>`<option value="${a.id}">${a.name} (${Utils.money(Storage.accountBalance(a.id))})</option>`).join('')||'<option value="">Add an account first</option>';depositModal.classList.add('show')}
  paint();addGoal.onclick=()=>goalModal.classList.add('show');closeGoal.onclick=()=>goalModal.classList.remove('show');closeDeposit.onclick=()=>depositModal.classList.remove('show');goalForm.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));Storage.add('goals',{...x,saved:0});goalModal.classList.remove('show');e.target.reset();paint();Utils.toast('Goal created.')};depositForm.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target)),amount=+x.amount,d=Storage.load(),g=d.goals.find(v=>v.id===activeGoalId);if(!g||!x.accountId||amount<=0)return Utils.toast('Choose an account and amount.');Storage.update('goals',g.id,{saved:(+g.saved||0)+amount});Storage.add('transactions',{type:'expense',amount,category:'Goal Transfer',accountId:x.accountId,date:new Date().toISOString().slice(0,10),description:'Deposit to '+g.name});depositModal.classList.remove('show');e.target.reset();paint();Utils.toast('Money added to '+g.name+'.')};
};
